#!/usr/bin/env python3
"""Apply trace-only cancellation hooks to the official SGLang 0.5.19 wheel."""

from __future__ import annotations

import argparse
import difflib
import shutil
from pathlib import Path


HELPER = '''# Generated by cancellation_audit/instrument_sglang_0519.py
from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime, timezone
from typing import Any

_ENABLED = os.environ.get("CANCEL_AUDIT_TRACE") == "1"
_PATH = os.environ.get("CANCEL_AUDIT_TRACE_FILE")
_MARKER = os.environ.get("CANCEL_AUDIT_REQUEST_PREFIX", "cancel-audit-")


def emit(request_id: str, event: str, *, iteration: int | None = None,
         running_count: int | None = None, extra: dict[str, Any] | None = None) -> None:
    request_id = str(request_id)
    if not _ENABLED or not _PATH or _MARKER not in request_id:
        return
    match = re.search(r"cancel-audit-[0-9a-f]{12}-[0-9]{6}-[0-9a-f]{8}", request_id)
    audit_id = match.group(0) if match else request_id
    row = {
        "ts_monotonic_ns": time.monotonic_ns(),
        "ts_wall": datetime.now(timezone.utc).isoformat(timespec="microseconds"),
        "runtime": "sglang",
        "source": "runtime",
        "evidence": "OBSERVED",
        "audit_id": audit_id,
        "runtime_request_id": request_id,
        "event": event,
        "iteration": iteration,
        "running_count": running_count,
        "extra": extra or {},
        "pid": os.getpid(),
    }
    payload = (json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\\n").encode()
    fd = os.open(_PATH, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    try:
        os.write(fd, payload)
    finally:
        os.close(fd)
'''


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


def patch_file(path: Path, transforms: list[tuple[str, str, str]], diff_dir: Path) -> None:
    backup = path.with_suffix(path.suffix + ".cancel_audit.orig")
    if backup.exists():
        original = backup.read_text(encoding="utf-8")
    else:
        original = path.read_text(encoding="utf-8")
        shutil.copy2(path, backup)
    updated = original
    for old, new, label in transforms:
        updated = replace_once(updated, old, new, label)
    path.write_text(updated, encoding="utf-8")
    diff_dir.mkdir(parents=True, exist_ok=True)
    diff = "".join(difflib.unified_diff(
        original.splitlines(True), updated.splitlines(True),
        fromfile=str(path) + ":upstream", tofile=str(path) + ":instrumented",
    ))
    (diff_dir / (path.name + ".diff")).write_text(diff, encoding="utf-8")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("package_root", type=Path, help=".../site-packages/sglang")
    p.add_argument("--diff-dir", type=Path, default=Path("results/phase1/provenance/sglang-0.5.19"))
    args = p.parse_args()
    root = args.package_root.resolve()
    (root / "_cancel_audit.py").write_text(HELPER, encoding="utf-8")

    tokenizer = root / "srt/managers/tokenizer_manager.py"
    patch_file(tokenizer, [
        (
            "from fastapi import BackgroundTasks\n",
            "from fastapi import BackgroundTasks\nfrom sglang._cancel_audit import emit as cancel_audit_emit\n",
            "tokenizer import",
        ),
        (
            "        req = AbortReq(rid=rid, abort_all=abort_all)\n        self._dispatch_to_scheduler(req)\n",
            "        req = AbortReq(rid=rid, abort_all=abort_all)\n"
            "        cancel_audit_emit(rid, \"ABORT_EMITTED\", extra={\"abort_all\": abort_all})\n"
            "        self._dispatch_to_scheduler(req)\n",
            "abort emission hook",
        ),
        (
            "        async def abort_request():\n            await asyncio.sleep(2)\n            if obj.is_single:\n                self.abort_request(obj.rid)\n            else:\n                for rid in obj.rid:\n                    self.abort_request(rid)\n",
            "        async def abort_request():\n"
            "            _audit_rids = [obj.rid] if obj.is_single else list(obj.rid)\n"
            "            for _audit_rid in _audit_rids:\n"
            "                cancel_audit_emit(_audit_rid, \"SERVER_DISCONNECT_DETECTED\", extra={\"observation\": \"streaming_response_background_started\"})\n"
            "            await asyncio.sleep(2)\n"
            "            if obj.is_single:\n"
            "                self.abort_request(obj.rid)\n"
            "            else:\n"
            "                for rid in obj.rid:\n"
            "                    self.abort_request(rid)\n",
            "disconnect hook",
        ),
        (
            "        if (\n            not abort_all\n            and get_serving().tokenizer_worker_num == 1\n            and rid not in self.rid_to_state\n        ):\n            return\n",
            "        if (\n            not abort_all\n            and get_serving().tokenizer_worker_num == 1\n            and rid not in self.rid_to_state\n        ):\n"
            "            cancel_audit_emit(rid, \"ABORT_DROPPED_NO_STATE\")\n"
            "            return\n",
            "abort guard hook",
        ),
        (
            "        for rid in rids:\n            self.rid_to_state.pop(rid, None)\n",
            "        for rid in rids:\n"
            "            cancel_audit_emit(rid, \"REQ_STATE_DISCARDED\", extra={\"was_present\": rid in self.rid_to_state})\n"
            "            self.rid_to_state.pop(rid, None)\n",
            "discard hook",
        ),
    ], args.diff_dir)

    scheduler = root / "srt/managers/scheduler.py"
    patch_file(scheduler, [
        (
            "from sglang.srt.utils.common import suppress_noisy_warnings  # isort: skip\n",
            "from sglang.srt.utils.common import suppress_noisy_warnings  # isort: skip\nfrom sglang._cancel_audit import emit as cancel_audit_emit  # isort: skip\n",
            "scheduler import",
        ),
        (
            "        batch.forward_iter = self.forward_ct\n        batch.launch_ts = time.monotonic()\n",
            "        batch.forward_iter = self.forward_ct\n"
            "        for _audit_req in batch.reqs:\n"
            "            cancel_audit_emit(_audit_req.rid, \"SCHEDULER_ITERATION\", iteration=self.forward_ct, running_count=len(batch.reqs), extra={\"forward_mode\": str(batch.forward_mode)})\n"
            "        batch.launch_ts = time.monotonic()\n",
            "scheduler iteration hook",
        ),
        (
            "    def abort_request(self, recv_req: AbortReq):\n        if (chunked_req := self.chunked_req) is not None:\n",
            "    def abort_request(self, recv_req: AbortReq):\n"
            "        cancel_audit_emit(recv_req.rid, \"SCHEDULER_ABORT_SEEN\", iteration=self.forward_ct, running_count=len(self.collect_inflight_reqs()), extra={\"abort_all\": recv_req.abort_all})\n"
            "        if (chunked_req := self.chunked_req) is not None:\n",
            "scheduler abort hook",
        ),
    ], args.diff_dir)

    common = root / "srt/mem_cache/common.py"
    patch_file(common, [
        (
            "from sglang.kernels.ops.memory.common import (\n",
            "from sglang._cancel_audit import emit as cancel_audit_emit\nfrom sglang.kernels.ops.memory.common import (\n",
            "cache import",
        ),
        (
            "    # StreamingSession.cache_finished_req handles speculative tail trim\n    # internally, then sets req_pool_idx = None.\n    assert (not req.kv.holds_kv) == req.kv.is_kv_released\n    if not req.kv.holds_kv:\n        return\n",
            "    # StreamingSession.cache_finished_req handles speculative tail trim\n"
            "    # internally, then sets req_pool_idx = None.\n"
            "    assert (not req.kv.holds_kv) == req.kv.is_kv_released\n"
            "    if not req.kv.holds_kv:\n"
            "        cancel_audit_emit(req.rid, \"KV_RELEASED\", extra={\"path\": \"prefix_cache\"})\n"
            "        return\n",
            "cached KV release hook",
        ),
        (
            "    req.kv.mark_kv_released()\n\n\ndef _release_overallocated_kv_indices(\n",
            "    req.kv.mark_kv_released()\n"
            "    cancel_audit_emit(req.rid, \"KV_RELEASED\", extra={\"path\": \"direct\"})\n\n\n"
            "def _release_overallocated_kv_indices(\n",
            "direct KV release hook",
        ),
    ], args.diff_dir)
    print(f"instrumented {root}")


if __name__ == "__main__":
    main()
