#!/usr/bin/env python3
"""Apply trace-only cancellation hooks to SGLang 0.5.19 + PR #35255 backport.

Expects the venv's tokenizer_manager.py / scheduler.py to already contain the
PR #35255 fix (see apply_pr35255 step in the run log). Emits the same event
types as instrument_sglang_0519.py plus fixed-path events
(REQ_STATE_RELEASED, ABORT_DEDUP_SKIPPED, ABORT_DROPPED_NO_STATE) so the
broken-vs-fixed A/B uses identical lifecycle analysis.
"""

from __future__ import annotations

import argparse
import difflib
import shutil
from pathlib import Path


HELPER = '''# Generated by cancellation_audit/instrument_sglang_fixed.py
from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime, timezone
from typing import Any

_ENABLED = os.environ.get("CANCEL_AUDIT_TRACE") == "1"
_PATH = os.environ.get("CANCEL_AUDIT_TRACE_FILE")
_MARKER = os.environ.get("CANCEL_AUDIT_REQUEST_PREFIX", "cancel-audit-")


def emit(request_id: str, event: str, *, iteration: int | None = None,
         running_count: int | None = None, extra: dict[str, Any] | None = None) -> None:
    request_id = str(request_id)
    if not _ENABLED or not _PATH or _MARKER not in request_id:
        return
    match = re.search(r"cancel-audit-[0-9a-f]{12}-[0-9]{6}-[0-9a-f]{8}", request_id)
    audit_id = match.group(0) if match else request_id
    row = {
        "ts_monotonic_ns": time.monotonic_ns(),
        "ts_wall": datetime.now(timezone.utc).isoformat(timespec="microseconds"),
        "runtime": "sglang",
        "source": "runtime",
        "evidence": "OBSERVED",
        "audit_id": audit_id,
        "runtime_request_id": request_id,
        "event": event,
        "iteration": iteration,
        "running_count": running_count,
        "extra": extra or {},
        "pid": os.getpid(),
    }
    payload = (json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\\n").encode()
    fd = os.open(_PATH, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    try:
        os.write(fd, payload)
    finally:
        os.close(fd)
'''


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


def patch_file(path: Path, transforms: list[tuple[str, str, str]], diff_dir: Path) -> None:
    backup = path.with_suffix(path.suffix + ".cancel_audit_fixed.orig")
    if backup.exists():
        original = backup.read_text(encoding="utf-8")
    else:
        original = path.read_text(encoding="utf-8")
        shutil.copy2(path, backup)
    updated = original
    for old, new, label in transforms:
        updated = replace_once(updated, old, new, label)
    path.write_text(updated, encoding="utf-8")
    diff_dir.mkdir(parents=True, exist_ok=True)
    diff = "".join(difflib.unified_diff(
        original.splitlines(True), updated.splitlines(True),
        fromfile=str(path) + ":pr35255", tofile=str(path) + ":instrumented",
    ))
    (diff_dir / (path.name + ".diff")).write_text(diff, encoding="utf-8")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("package_root", type=Path, help=".../site-packages/sglang")
    p.add_argument("--diff-dir", type=Path, default=Path("results/fixed/provenance"))
    args = p.parse_args()
    root = args.package_root.resolve()
    (root / "_cancel_audit.py").write_text(HELPER, encoding="utf-8")

    tokenizer = root / "srt/managers/tokenizer_manager.py"
    patch_file(tokenizer, [
        (
            "from fastapi import BackgroundTasks\n",
            "from fastapi import BackgroundTasks\nfrom sglang._cancel_audit import emit as cancel_audit_emit\n",
            "tokenizer import",
        ),
        # Hand-applied hunk that patch(1) rejected: the method definition.
        (
            "    def _send_batch_request(\n",
            "    def _mark_state_dispatched(self, rid: str):\n"
            "        \"\"\"Record that *rid* reached the scheduler (backport of PR #35255).\"\"\"\n"
            "        state = self.rid_to_state.get(rid)\n"
            "        if state is not None:\n"
            "            state.dispatched = True\n"
            "\n"
            "    def _send_batch_request(\n",
            "mark_state_dispatched def",
        ),
        (
            "        async def abort_request():\n            await asyncio.sleep(2)\n            rids = [obj.rid] if obj.is_single else obj.rid\n            for rid in rids:\n                if rid in self.rid_to_state:\n                    self.abort_request(rid)\n",
            "        async def abort_request():\n"
            "            _audit_rids = [obj.rid] if obj.is_single else list(obj.rid)\n"
            "            for _audit_rid in _audit_rids:\n"
            "                cancel_audit_emit(_audit_rid, \"SERVER_DISCONNECT_DETECTED\", extra={\"observation\": \"streaming_response_background_started\"})\n"
            "            await asyncio.sleep(2)\n"
            "            rids = [obj.rid] if obj.is_single else obj.rid\n"
            "            for rid in rids:\n"
            "                if rid in self.rid_to_state:\n"
            "                    self.abort_request(rid)\n",
            "disconnect hook",
        ),
        (
            "        for rid in rids:\n            state = self.rid_to_state.get(rid)\n            if state is None:\n                continue\n            if state.dispatched:\n",
            "        for rid in rids:\n"
            "            state = self.rid_to_state.get(rid)\n"
            "            if state is None:\n"
            "                continue\n"
            "            cancel_audit_emit(rid, \"REQ_STATE_RELEASED\", extra={\"was_dispatched\": state.dispatched})\n"
            "            if state.dispatched:\n",
            "release hook",
        ),
        (
            "            if state is not None:\n                if state.abort_sent:\n                    return\n                state.abort_sent = True\n            elif get_serving().tokenizer_worker_num == 1:\n                return\n",
            "            if state is not None:\n"
            "                if state.abort_sent:\n"
            "                    cancel_audit_emit(rid, \"ABORT_DEDUP_SKIPPED\")\n"
            "                    return\n"
            "                state.abort_sent = True\n"
            "            elif get_serving().tokenizer_worker_num == 1:\n"
            "                cancel_audit_emit(rid, \"ABORT_DROPPED_NO_STATE\")\n"
            "                return\n",
            "abort guard hooks",
        ),
        (
            "        req = AbortReq(rid=rid, abort_all=abort_all)\n        try:\n",
            "        req = AbortReq(rid=rid, abort_all=abort_all)\n"
            "        cancel_audit_emit(rid, \"ABORT_EMITTED\", extra={\"abort_all\": abort_all})\n"
            "        try:\n",
            "abort emission hook",
        ),
    ], args.diff_dir)

    scheduler = root / "srt/managers/scheduler.py"
    patch_file(scheduler, [
        (
            "from sglang.srt.utils.common import suppress_noisy_warnings  # isort: skip\n",
            "from sglang.srt.utils.common import suppress_noisy_warnings  # isort: skip\nfrom sglang._cancel_audit import emit as cancel_audit_emit  # isort: skip\n",
            "scheduler import",
        ),
        (
            "        batch.forward_iter = self.forward_ct\n        batch.launch_ts = time.monotonic()\n",
            "        batch.forward_iter = self.forward_ct\n"
            "        for _audit_req in batch.reqs:\n"
            "            cancel_audit_emit(_audit_req.rid, \"SCHEDULER_ITERATION\", iteration=self.forward_ct, running_count=len(batch.reqs), extra={\"forward_mode\": str(batch.forward_mode)})\n"
            "        batch.launch_ts = time.monotonic()\n",
            "scheduler iteration hook",
        ),
        (
            "    def abort_request(self, recv_req: AbortReq):\n        if (chunked_req := self.chunked_req) is not None:\n",
            "    def abort_request(self, recv_req: AbortReq):\n"
            "        cancel_audit_emit(recv_req.rid, \"SCHEDULER_ABORT_SEEN\", iteration=self.forward_ct, running_count=len(self.collect_inflight_reqs()), extra={\"abort_all\": recv_req.abort_all})\n"
            "        if (chunked_req := self.chunked_req) is not None:\n",
            "scheduler abort hook",
        ),
    ], args.diff_dir)
    print(f"instrumented {root} (fixed)")


if __name__ == "__main__":
    main()
