#!/usr/bin/env python3
"""Apply trace-only cancellation hooks to the official vLLM 0.28.0 wheel.

The patch is guarded by CANCEL_AUDIT_TRACE=1 and filters request IDs that start
with ``cancel-audit-``. It does not modify scheduling or reclamation decisions.
"""

from __future__ import annotations

import argparse
import difflib
import shutil
from pathlib import Path


HELPER = '''# Generated by cancellation_audit/instrument_vllm_028.py
from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime, timezone
from typing import Any

_ENABLED = os.environ.get("CANCEL_AUDIT_TRACE") == "1"
_PATH = os.environ.get("CANCEL_AUDIT_TRACE_FILE")
_PREFIX = os.environ.get("CANCEL_AUDIT_REQUEST_PREFIX", "cancel-audit-")


def emit(request_id: str, event: str, *, iteration: int | None = None,
         running_count: int | None = None, extra: dict[str, Any] | None = None) -> None:
    request_id = str(request_id)
    if not _ENABLED or not _PATH or _PREFIX not in request_id:
        return
    match = re.search(r"cancel-audit-[0-9a-f]{12}-[0-9]{6}-[0-9a-f]{8}", request_id)
    audit_id = match.group(0) if match else request_id
    row = {
        "ts_monotonic_ns": time.monotonic_ns(),
        "ts_wall": datetime.now(timezone.utc).isoformat(timespec="microseconds"),
        "runtime": "vllm",
        "source": "runtime",
        "evidence": "OBSERVED",
        "audit_id": audit_id,
        "runtime_request_id": request_id,
        "event": event,
        "iteration": iteration,
        "running_count": running_count,
        "extra": extra or {},
        "pid": os.getpid(),
    }
    payload = (json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\\n").encode()
    fd = os.open(_PATH, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    try:
        os.write(fd, payload)
    finally:
        os.close(fd)
'''


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


def patch_file(path: Path, transforms: list[tuple[str, str, str]], diff_dir: Path) -> None:
    original_path = path.with_suffix(path.suffix + ".cancel_audit.orig")
    if original_path.exists():
        original = original_path.read_text(encoding="utf-8")
    else:
        original = path.read_text(encoding="utf-8")
        shutil.copy2(path, original_path)
    updated = original
    for old, new, label in transforms:
        updated = replace_once(updated, old, new, label)
    path.write_text(updated, encoding="utf-8")
    diff = "".join(difflib.unified_diff(
        original.splitlines(True), updated.splitlines(True),
        fromfile=str(path) + ":upstream", tofile=str(path) + ":instrumented",
    ))
    diff_dir.mkdir(parents=True, exist_ok=True)
    (diff_dir / (path.name + ".diff")).write_text(diff, encoding="utf-8")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("package_root", type=Path, help=".../site-packages/vllm")
    p.add_argument("--diff-dir", type=Path, default=Path("results/phase1/provenance/vllm-0.28.0"))
    args = p.parse_args()
    root = args.package_root.resolve()
    (root / "_cancel_audit.py").write_text(HELPER, encoding="utf-8")

    serving = root / "entrypoints/openai/chat_completion/serving.py"
    patch_file(serving, [
        (
            "from vllm.engine.protocol import EngineClient\n",
            "from vllm._cancel_audit import emit as cancel_audit_emit\nfrom vllm.engine.protocol import EngineClient\n",
            "serving import",
        ),
        (
            "        except GenerationError as e:\n",
            "        except asyncio.CancelledError:\n"
            "            cancel_audit_emit(request_id, \"FRONTEND_STREAM_CANCELLED_POST_ABORT\", extra={\"observation\": \"stream_generator_cancelled\"})\n"
            "            raise\n"
            "        except GenerationError as e:\n",
            "stream cancellation hook",
        ),
    ], args.diff_dir)

    async_llm = root / "v1/engine/async_llm.py"
    patch_file(async_llm, [
        (
            "import vllm.envs as envs\n",
            "import vllm.envs as envs\nfrom vllm._cancel_audit import emit as cancel_audit_emit\n",
            "async_llm import",
        ),
        (
            "        except (asyncio.CancelledError, GeneratorExit):\n"
            "            if q is not None:\n"
            "                await self.abort(q.request_id, internal=True)\n"
            "            if self.log_requests:\n"
            "                logger.info(\"Request %s aborted.\", request_id)\n",
            "        except (asyncio.CancelledError, GeneratorExit):\n"
            "            if q is not None:\n"
            "                cancel_audit_emit(q.request_id, \"SERVER_DISCONNECT_DETECTED\", extra={\"observation\": \"engine_generator_cancelled\"})\n"
            "                cancel_audit_emit(q.request_id, \"ABORT_EMITTED\", extra={\"internal\": True})\n"
            "                await self.abort(q.request_id, internal=True)\n"
            "            if self.log_requests:\n"
            "                logger.info(\"Request %s aborted.\", request_id)\n",
            "abort emission hook",
        ),
    ], args.diff_dir)

    scheduler = root / "v1/core/sched/scheduler.py"
    patch_file(scheduler, [
        (
            "from vllm.compilation.cuda_graph import CUDAGraphStat\n",
            "from vllm._cancel_audit import emit as cancel_audit_emit\nfrom vllm.compilation.cuda_graph import CUDAGraphStat\n",
            "scheduler import",
        ),
        (
            "        scheduler_output = SchedulerOutput(\n",
            "        for _audit_req_id, _audit_tokens in num_scheduled_tokens.items():\n"
            "            cancel_audit_emit(_audit_req_id, \"SCHEDULER_ITERATION\", iteration=self.current_step, running_count=len(self.running), extra={\"num_scheduled_tokens\": _audit_tokens})\n\n"
            "        scheduler_output = SchedulerOutput(\n",
            "scheduler iteration hook",
        ),
        (
            "            valid_requests.append(request)\n            if request.status == RequestStatus.RUNNING:\n",
            "            valid_requests.append(request)\n"
            "            if finished_status == RequestStatus.FINISHED_ABORTED:\n"
            "                cancel_audit_emit(req_id, \"SCHEDULER_ABORT_SEEN\", iteration=self.current_step, running_count=len(self.running), extra={\"prior_status\": str(request.status)})\n"
            "            if request.status == RequestStatus.RUNNING:\n",
            "scheduler abort hook",
        ),
        (
            "        del self.requests[request.request_id]\n",
            "        del self.requests[request.request_id]\n"
            "        cancel_audit_emit(request.request_id, \"KV_RELEASED\", iteration=self.current_step, running_count=len(self.running), extra={\"request_state_deleted\": True})\n",
            "KV release hook",
        ),
    ], args.diff_dir)
    print(f"instrumented {root}")


if __name__ == "__main__":
    main()
